### ISSUE TITLE
How do we override the default public layout?

### ISSUE THREAD

**Issue by aaronmase** [radiant/radiant-share-layouts-extension#3]
How do we override the default public layout?  I have updated config/environment.rb to load share_layouts first, and have created a layout called normal.rhtml in share_layouts/app/view/layouts but there seems to be no effect.

**Comment by saturnflyer** [comment]
radiant uses the standard rails name of "application" so just create a file in your_extension/app/views/layouts/application.html.haml

**Comment by saturnflyer** [comment]
this was dumb. i commented and closed without thinking enough. reopening...
