### ISSUE TITLE
Gotcha in combination with 'file system resources' extension

### ISSUE THREAD

**Issue by sjorsbranderhorst** [radiant/radiant-share-layouts-extension#4]
Say you are using the 'File System Resources' extension and you have created a layout file by the name of Two-Column. Now when you want to share this layout in a custom extension view make sure the radiant_layout declaration looks like:

class MagazinesController < ApplicationController
  ....

  radiant_layout '[FS] Two-Column'
    ...
end

that.

**Comment by saturnflyer** [comment]
this doesn't seem like an issue with this extension but with file system resources
